### ISSUE TITLE
Rebuild image when `--keep` is fixed

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/docker-zenodo#1]
The `--keep` option in `zenodo_get` does not seem to be working as expected ([issue](https://github.com/dvolgyes/zenodo_get/issues/29)), effectively doing a `force_pull` all the time.

When the issue is fixed from their side, rebuild the image with the latest `zenodo_get`

**Comment by serasset** [comment]
Seems to be an issue in your understanding of the keep option...

**Comment by IgnacioHeredia** [comment]
Closed because we moved to Datahugger
